// These are the items that will be displayed in the shop. You can add more items to this array as needed.


const items = [
  { name: "Crochet Hat",       price: 500,  img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKDFWKefgLHb0uaLVrtm8M_dPjLLasRoYwTg&s",        description: "A cozy hand-crocheted hat, perfect for casual outings." },
  { name: "Hand Bag",          price: 1200, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1fGc3RGXm6XBbDulvkdnFo7vXnAA-3Yb4sA&s",     description: "Stylish handmade handbag to carry your essentials in style." },
  { name: "Wind Spinner",      price: 300,  img: "https://scontent.fnbo18-1.fna.fbcdn.net/v/t51.82787-15/649651834_17858949984668452_7927647422749340069_n.webp?stp=dst-jpg_tt6&_nc_cat=108&ccb=1-7&_nc_sid=13d280&_nc_eui2=AeE4Tnd8xPRLj8k9yR3-VFinhtxjAWSS6sCG3GMBZJLqwA2cy2hwj03QmFvuagyEGlMjR0zzJBkqncZ0KfLGngeI&_nc_ohc=6oVkrPG4auUQ7kNvwFMYD7N&_nc_oc=Adq_0BDUr6WPJG3ebp_984-Nr7Cg-_lzlddF4XPZfOzveSdZY1wP6Z4j9X1Rg8D1MrV1wVerVlGOY85oRss1N4W4&_nc_zt=23&_nc_ht=scontent.fnbo18-1.fna&_nc_gid=PtCgS3jWUNlsqOeyn-Zdmg&_nc_ss=8&oh=00_AfwOF-qik6X_9QfycpQSd9lQcsX4zW4DHzlHvKakLe3YZg&oe=69C20E80",     description: "A colorful wind spinner to brighten up your garden or balcony." },
  { name: "Vintage Mug",       price: 400,  img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk9LbZlFQF0MpmWy754Gl-JbZNiTZVcxYd0g&s",         description: "Classic vintage mug, ideal for your morning coffee or tea." },
  { name: "Decorative Vase",   price: 800,  img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSU0PaBeaNUNa8FIQD05xWXr47d-0ARGt4LdA&s",        description: "Elegant vase to display flowers or as a decorative centerpiece." },
  { name: "Retro Clock",       price: 1500, img: "https://i5.walmartimages.com/seo/5-5-Classic-Retro-Clock-Saytay-European-Vintage-Silent-Desk-Analog-Alarm-Non-Ticking-Quartz-Movement-Battery-Operated-Glass-Lens-Easy-To-Read-Bronze_577f1398-276a-4070-bdb0-35f07850edca.bdc91617311eaa527dc514198a615b98.jpeg",  description: "A retro-style clock to add a nostalgic touch to any room." },
  { name: "Handmade Candle",   price: 350,  img: "https://www.saffronmarigold.com/catalog/images/product_detail/artisan_handmade_candles_white_pillar_detail1.jpg",      description: "Scented handmade candle to create a relaxing atmosphere." },
  { name: "Mini Plant Pot",    price: 250,  img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4Yf_sRkJEjV0MYY-9CUGX4k_yhs_0CFhuwA&s",    description: "Small plant pot, perfect for succulents or tiny indoor plants." },
  { name: "Art Print",         price: 1000, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKTvF4Tqk93wGtT7Cj3IN8xD2jNBhUARTvRg&s",    description: "High-quality art print to decorate your walls beautifully." },
  { name: "Leather Wallet",    price: 900,  img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeD5g1Ix8lDdU9eHNiAfmSHKOn3N7d_xVM7g&s",      description: "Durable leather wallet with multiple compartments." },
  { name: "Knitted Scarf",     price: 600,  img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKHEyIlVDTGd-MK_XUZFiJO7ussUihR-HAtQ&s",       description: "Warm knitted scarf, perfect for cold weather." },
  { name: "Wooden Key Holder", price: 400,  img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoo-8DR9zfwH3va2G4Q5DAPqbsaDPQ_Jv5FUJs5Ql0NQ&s",   description: "Handcrafted wooden key holder to keep your keys organized." },
  { name: "Decorative Pillow", price: 700,  img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpqayHUDDyM72dB4kMFW3sE4ISX2Gc3P4JLw&s",      description: "Soft decorative pillow to add color and comfort to your home." },
  { name: "Ceramic Plate",     price: 350,  img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSibr7R9p37xYNEKeZShLIPi4QTqeQochCAWQ&s",     description: "Beautiful ceramic plate for serving or decoration." },
  { name: "Mini Backpack",     price: 1100, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLz5--0MufeSalyrDILeAM07LpCVujRoBdag&s",    description: "Compact and stylish mini backpack for daily use." },
  { name: "Scented Soap",      price: 200,  img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpxauqWQnK3rPRfPXEGCUq2D9BWN7X9FTLBQ&s",        description: "Handmade scented soap with a refreshing fragrance." },
  { name: "Wall Hanging",      price: 950,  img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQP65iRNkiLQv9lj_ZI7SIQQzmKtL9yQhyOrw&s",    description: "Artistic wall hanging to enhance any room's décor." },
  { name: "Decorative Jar",    price: 550,  img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_IrPsp_Ki9vgTkpbqJFvaTHmJ0no5NcsxOQ&s",         description: "Glass jar that doubles as decoration or storage." },
  { name: "Canvas Tote",       price: 650,  img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQj7bjjVvGLkoH7QnWIQxDj_ItQuy_an-zjPg&s",        description: "Eco-friendly canvas tote for shopping or casual use." },
  { name: "Desk Organizer",    price: 800,  img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZuKn6nh7SQS9Fds6gKStQpaekuQ9Os2ckVw&s",   description: "Keep your desk tidy with this practical organizer." },
];

export default items;